version: '3.8'
services:
  vapi:
    build: 
      context: ./vapi  # folder with the VAPI Dockerfile & source
    container_name: vapi
    ports:
      - "9090:9090"
    networks:
      - mynet
    
  gateway:
    build: 
      context: ./gateway  # folder with the Dockerfile & pi_gateway.py
    container_name: gateway
    depends_on:
      - vapi
      - broker
    networks:
      - mynet
    # environment:
    #   - VAPI_HOST=vapi
    #   - VAPI_PORT=9090
  
  broker:
    build:
      context: ./broker
    container_name: broker
    ports:
      - "1883:1883"

networks:
  mynet:
    driver: bridge
